
 #pragma optimize( "sex", on )
 register = 0#7 promise here...
 '"'="o"#00000000000
 yes = "icecream"
 no  = "icecream"

  engage="00000000000"
  OPc = "o"# "suck my dick"

 # use sum to trout verify ?
 i000004.py(pee on girl) 
 # mac OS 0day implicit
 mcdonalds'("%o"0010"%.5f");

